Add JUPYTERHUB_LOGIN_URL to JSP service
opendatahub-io/jupyterhub-odh pull request #95
Opened 2021-06-02 16:00 UTC by vpavlin

## Related Issues and Dependencies

## This introduces a breaking change

- [ ] Yes
- [ ] No

## This Pull Request implements

… Explain your changes.

## Description

2021-06-02 18:23 UTC, LaVLaS commented
This does fix the issue I encountered with `logout/login` not allowing someone to login as the same or different user

2021-06-02 19:11 UTC, crobby approved these changes

2021-06-03 12:31 UTC, crobby reviewed
change from using vpavlin github to official?

2021-06-03 12:32 UTC, LaVLaS requested changes

2021-06-03 12:32 UTC, LaVLaS commented on Pipfile
> +jupyterhub-singleuser-profiles = {ref = "bug/add-jupyter-login-url",git = "https://github.com/vpavlin/jupyterhub-singleuser-profiles.git", editable = true}
We just need to update this to the official commit

2021-06-03 16:03 UTC, merged